In [1]:
import pandas as pd
print("Pandas version:", pd.__version__)

Pandas version: 2.3.3

In [3]:
import pandas as pd

# Create a mock dictionary of retail data with all numbers included
data = {
    'Transaction_ID': [101, 102, 103, 104, 105, 106],
    'Product': ['Laptop', 'Headphones', 'Coffee Maker', 'Running Shoes', 'Desk Lamp', 'Headphones'],
    'Category': ['Electronics', 'Electronics', 'Home', 'Apparel', 'Home', 'Electronics'],
    'Price': [1200, 150, 80, 120, 30, 150],
    'Quantity': [1, 2, 1, 2, 3, 1]
}

# Turn the dictionary into a Pandas DataFrame (table)
df = pd.DataFrame(data)

# View the first few rows of our table
df.head()

   Transaction_ID        Product     Category  Price  Quantity
0             101         Laptop  Electronics   1200         1
1             102     Headphones  Electronics    150         2
2             103   Coffee Maker         Home     80         1
3             104  Running Shoes      Apparel    120         2
4             105      Desk Lamp         Home     30         3

In [4]:
# Check how many rows and columns we have (Rows, Columns)
print("Data Shape:", df.shape)

# Check data types and see if there are missing values (like SQL's schema info)
df.info()

Data Shape: (6, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  6 non-null      int64
 1   Product         6 non-null      object
 2   Category        6 non-null      object
 3   Price           6 non-null      int64
 4   Quantity        6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

In [5]:
# Multiply Price column by Quantity column
df['Total_Revenue'] = df['Price'] * df['Quantity']

# View the updated table
df

   Transaction_ID        Product     Category  Price  Quantity  Total_Revenue
0             101         Laptop  Electronics   1200         1           1200
1             102     Headphones  Electronics    150         2            300
2             103   Coffee Maker         Home     80         1             80
3             104  Running Shoes      Apparel    120         2            240
4             105      Desk Lamp         Home     30         3             90
5             106     Headphones  Electronics    150         1            150

In [6]:
# Filter rows where Category is 'Electronics'
electronics_df = df[df['Category'] == 'Electronics']

# View the filtered table
electronics_df

   Transaction_ID     Product     Category  Price  Quantity  Total_Revenue
0             101      Laptop  Electronics   1200         1           1200
1             102  Headphones  Electronics    150         2            300
5             106  Headphones  Electronics    150         1            150

In [7]:
# Filter rows where Total_Revenue is greater than 100
expensive_sales = df[df['Total_Revenue'] > 100]

# View the filtered table
expensive_sales

   Transaction_ID        Product     Category  Price  Quantity  Total_Revenue
0             101         Laptop  Electronics   1200         1           1200
1             102     Headphones  Electronics    150         2            300
3             104  Running Shoes      Apparel    120         2            240
5             106     Headphones  Electronics    150         1            150

In [8]:
# Filter for Home category AND quantity > 1
home_bulk_sales = df[(df['Category'] == 'Home') & (df['Quantity'] > 1)]

# View the filtered table
home_bulk_sales

   Transaction_ID    Product Category  Price  Quantity  Total_Revenue
4             105  Desk Lamp     Home     30         3             90

In [9]:
# Group by Category and sum up the Total_Revenue column
category_revenue = df.groupby('Category')['Total_Revenue'].sum()

# View the result
print("Total Revenue by Category:")
print(category_revenue)

Total Revenue by Category:
Category
Apparel         240
Electronics    1650
Home            170
Name: Total_Revenue, dtype: int64

In [10]:
# Group by Category and find the mean (average) of the Price column
category_avg_price = df.groupby('Category')['Price'].mean()

# View the result
print("\nAverage Price by Category:")
print(category_avg_price)

Average Price by Category:
Category
Apparel        120.0
Electronics    500.0
Home            55.0
Name: Price, dtype: float64

In [11]:
# Group by Category and count the Transaction_IDs
category_counts = df.groupby('Category')['Transaction_ID'].count()

# View the result
print("\nTransaction Count by Category:")
print(category_counts)

Transaction Count by Category:
Category
Apparel        1
Electronics    3
Home           2
Name: Transaction_ID, dtype: int64